# add some logging or something so can see what failure is
# change name of this file
# seperate into different steps
name: Terraform Deploy

on:
    workflow_dispatch:
      inputs:
        do-plan:
          description: 'Do terraform apply'
          type: boolean
          required: true
          default: false
        directory:
          description: 'Directory where terraform is'
          required: true

jobs:
  lint-sec:
    name: 'Lint & Security Check'
    # choose ubuntu version
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ${{ github.event.inputs.directory }}

    env:
      AWS_REGION: 'eu-west-2'
      # sort out versions here
      TF_VERSION: '1.4.0'
      TFLINT_VERSION: '0.46.0'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Install TFLint'
      run: |
        curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
        unzip tflint.zip -d /usr/local/bin/
        tflint --version
      working-directory: .

    - name: 'Install Checkov'
      #potentially add version here if i can
      run: |
        pip install checkov

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Format'
      run: terraform fmt

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'TFLint'
      run: |
        tflint --init
        tflint
    
    - name: 'Checkov'
      run: checkov -d .
    
    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan

    - name: 'Terraform Apply'
      if: ${{ github.event.inputs.do-plan }} == true
      run: terraform apply -auto-approve tfplan

